[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://slinkit.onrender.com"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Expose-Headers = "Set-Cookie"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200